server: 
  port: 6001
 
spring: 
  application:
    name: micro-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: micro-zuul-gateway
    prefer-ip-address: true 
 
 
  #ignored-services: microservicecloud-dept
zuul:
  prefix: /micro
  ignored-services: '*'
  routes: 
    mydept.serviceId: micro-provider
    mydept.path: /mydept/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

