eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/

spring:
  application:
    name: application-consumer-fegin-config

#不生效
#feign:
#  hystrix:
#    enabled: true

